### ISSUE TITLE
Dando tela preta no ps2 real

### ISSUE THREAD

**Issue by Gui8900** [DanielSant0s/AthenaEnv#26]
Quando eu abro o Athena.ELF no Ulanchelf ele fica com tela preta como fasso pra arrumar e fazer ele funciona? Nenhum dos ELF funciona (que estão na pasta que tu disponibilizou o download).

**Comment by DanielSant0s** [comment]
Não sei, aqui e com vários outros usuários está funcionando normalmente, talvez seja sua versão do uLaunchElf

**Comment by Gui8900** [comment]
Opa foi mal a demora, Não eu descobri o problema era: No ule tinha que
configurar o IP e a Dns internet sabe, esse era o problema

Em 23 de jun de 2023 10:17 AM, "Daniel Santos" ***@***.***>
escreveu:
