### ISSUE TITLE
Can I use this to port games from famous engines?

### ISSUE THREAD

**Issue by Pedro1234-code** [DanielSant0s/AthenaEnv#30]
Can this be used to port games made in famous engines like Construct or RPG Maker MV?

**Comment by terremoth** [comment]
Definitely no. Other engines probably will have many requirements and feature-specific from it.
You will need to re-write your own. 

Also, we don't have a 3D render via VU1 neither a 2D lib for physics neither more than 1 thread instance

**Comment by romancolor1225** [comment]
What if the game has JavaScript code (for example: Gdevelop), and the game is less demanding on hardware?
