### ISSUE TITLE
Can Athena launch an elf?

### ISSUE THREAD

**Issue by LuisHCK** [DanielSant0s/AthenaEnv#47]
I'm wondering if Athena can launch a ELF file like Enceladus?

`System.loadELF(path, reboot_iop, args...)`
https://github.com/DanielSant0s/Enceladus?tab=readme-ov-file#system-functions

**Comment by devingDev** [comment]
If you look into the main.js you will see how it starts the other scripts

**Comment by LuisHCK** [comment]
thanks @devingDev that's exactly what i'm looking for
