### ISSUE TITLE
Blank screen on actual hardware using uLE 4.42d

### ISSUE THREAD

**Issue by jcnmsg** [DanielSant0s/AthenaEnv#5]
Sorry to open yet another issue but have you had any luck running Athena projects on actual hardware? I have a FAT SCPH 39004 (PAL) and I'm running uLE 4.42d but every time I open the `.elf` file I see nothing but a blank screen. My TV displays both PAL and NTSC signals so that's not it.

[This](https://github.com/jcnmsg/T-Rex-PS2) is the project I'm trying to run but I also tried the code from #4 and the demo included with this repository and neither of them run, they just hang on a blank screen.

Is there anything I'm missing or are there any extra steps to running this on real hardware other than launching the `.elf` file?

**Comment by DanielSant0s** [comment]
can you test the artifact build from taskman branch, tell me if it works, thanks in advance

**Comment by jcnmsg** [comment]
Good job! Compiled the code on the taskman branch locally and it worked flawlessly! Thank you very much, will close this now!
